
package parfrvi_toko_pbo_if21c;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.lang.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.*;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.util.JRLoader.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.export.*;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JRException;
import java.awt.*;
import java.util.HashMap;
import java.lang.NullPointerException;
import java.io.FileNotFoundException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.lang.Object;


public class Arf_Aplikasi_Utama extends javax.swing.JFrame {
    Connection c;
    ResultSet r;
    Statement s;


    public Arf_Aplikasi_Utama() {
        initComponents();
        BukaKoneksi();
        SetMenu(true);
    }
    
    private void BukaKoneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost/db_toko_pbo_if21c","root","");
            System.out.println("Koneksi sukses");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    private void ArifMasuk(){
        try{
            String nama=arf_username.getText();
            String pass=new String(arf_password.getPassword());
            s=c.createStatement();
            
            String sql="Select*from arfrvi_login where arf_username='"+nama+"' And arf_password='"+pass+"'";
            
            r=s.executeQuery(sql);
            int baris=0;
            while(r.next()){
                baris=r.getRow();
            }
            if(baris==1){
                SetMenu(false);
                BersihField();
            }
            else{
                SetMenu(true);
                BersihField();
                JOptionPane.showMessageDialog(null,"Login Gagal");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void SetMenu(boolean b){
        arf_mfile.setEnabled(!b);
        arf_mmaster.setEnabled(!b);
        arf_mtrans.setEnabled(!b);
        arf_mlap.setEnabled(!b);
    }
    private void BersihField(){
        arf_username.setText("");
        arf_password.setText("");
        
    }
    
    private void ExitWindow(){
        int confirmed = JOptionPane.showConfirmDialog
            (null, "Keluar Dari Program?","Exit",JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
        }else
           {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
           }
       }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arf_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        arf_bt_masuk = new javax.swing.JButton();
        arf_bt_batal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        arf_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        arf_mfile = new javax.swing.JMenu();
        arf_sm_new = new javax.swing.JMenuItem();
        arf_sm_open = new javax.swing.JMenuItem();
        arf_sm_save = new javax.swing.JMenuItem();
        arf_sm_saveas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        arf_sm_psswrd = new javax.swing.JMenuItem();
        arf_sm_keluar = new javax.swing.JMenuItem();
        arf_mmaster = new javax.swing.JMenu();
        arf_mstr_brg = new javax.swing.JMenuItem();
        arf_mstr_sup = new javax.swing.JMenuItem();
        arf_mstr_peg = new javax.swing.JMenuItem();
        arf_mtrans = new javax.swing.JMenu();
        arf_trans_beli = new javax.swing.JMenuItem();
        arf_trans_jual = new javax.swing.JMenuItem();
        arf_mlap = new javax.swing.JMenu();
        arf_lap_inti = new javax.swing.JMenu();
        arf_lap_tblbrg = new javax.swing.JMenuItem();
        arf_lap_tblsup = new javax.swing.JMenuItem();
        arf_lap_tblpeg = new javax.swing.JMenuItem();
        arf_lap_tblbeli = new javax.swing.JMenuItem();
        arf_lap_tbljual = new javax.swing.JMenuItem();
        arf_lap_gab = new javax.swing.JMenu();
        arf_gab2tbl = new javax.swing.JMenuItem();
        arf_gab3tbl = new javax.swing.JMenuItem();
        arf_gab4tbl = new javax.swing.JMenuItem();
        arf_gab5tbl = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Utama");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel1.setText("MASUKAN USER NAME DAN PASSWORD");

        jLabel2.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel2.setText("APLIKASI BISNIS");

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel3.setText("MINI MARKET");

        arf_username.setName("arf_username"); // NOI18N
        arf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_usernameActionPerformed(evt);
            }
        });
        arf_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                arf_usernameKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel4.setText("PASSWORD");

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel5.setText("USERNAME");

        arf_bt_masuk.setText("MASUK");
        arf_bt_masuk.setName("arf_bt_masuk"); // NOI18N
        arf_bt_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_bt_masukActionPerformed(evt);
            }
        });

        arf_bt_batal.setText("BATAL");
        arf_bt_batal.setName("arf_bt_batal"); // NOI18N
        arf_bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_bt_batalActionPerformed(evt);
            }
        });

        jLabel6.setText("Produced  By Arif");

        arf_password.setName("arf_password"); // NOI18N

        jLabel7.setText("Username : Arif");

        jLabel8.setText("Password : 123");

        arf_mfile.setText("File");
        arf_mfile.setName("arf_mfile"); // NOI18N

        arf_sm_new.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        arf_sm_new.setText("New");
        arf_sm_new.setName("arf_sm_new"); // NOI18N
        arf_sm_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_sm_newActionPerformed(evt);
            }
        });
        arf_mfile.add(arf_sm_new);

        arf_sm_open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        arf_sm_open.setText("Open");
        arf_sm_open.setName("arf_sm_open"); // NOI18N
        arf_mfile.add(arf_sm_open);

        arf_sm_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        arf_sm_save.setText("Save");
        arf_sm_save.setName("arf_sm_save"); // NOI18N
        arf_sm_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_sm_saveActionPerformed(evt);
            }
        });
        arf_mfile.add(arf_sm_save);

        arf_sm_saveas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        arf_sm_saveas.setText("Save As");
        arf_sm_saveas.setName("arf_sm_saveas"); // NOI18N
        arf_mfile.add(arf_sm_saveas);
        arf_mfile.add(jSeparator1);

        arf_sm_psswrd.setText("Ubah Password");
        arf_sm_psswrd.setName("arf_sm_psswrd"); // NOI18N
        arf_mfile.add(arf_sm_psswrd);

        arf_sm_keluar.setText("Keluar");
        arf_sm_keluar.setName("arf_sm_keluar"); // NOI18N
        arf_mfile.add(arf_sm_keluar);

        jMenuBar2.add(arf_mfile);

        arf_mmaster.setText("Master");
        arf_mmaster.setName("arf_master"); // NOI18N

        arf_mstr_brg.setText("Aplikasi Master Barang");
        arf_mstr_brg.setName("arf_mstr_brg"); // NOI18N
        arf_mstr_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_mstr_brgActionPerformed(evt);
            }
        });
        arf_mmaster.add(arf_mstr_brg);

        arf_mstr_sup.setText("Aplikasi Master Supplier");
        arf_mstr_sup.setName("arf_mstr_sup"); // NOI18N
        arf_mstr_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_mstr_supActionPerformed(evt);
            }
        });
        arf_mmaster.add(arf_mstr_sup);

        arf_mstr_peg.setText("Aplikasi Master Pegawai");
        arf_mstr_peg.setName("arf_mstr_peg"); // NOI18N
        arf_mstr_peg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_mstr_pegActionPerformed(evt);
            }
        });
        arf_mmaster.add(arf_mstr_peg);

        jMenuBar2.add(arf_mmaster);

        arf_mtrans.setText("Transaksi");
        arf_mtrans.setName("arf_transaksi"); // NOI18N

        arf_trans_beli.setText("Aplikasi Transaksi Pembelian");
        arf_trans_beli.setName("arf_trans_beli"); // NOI18N
        arf_trans_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_trans_beliActionPerformed(evt);
            }
        });
        arf_mtrans.add(arf_trans_beli);

        arf_trans_jual.setText("Aplikasi Transaksi Penjual");
        arf_trans_jual.setName("arf_trans_jual"); // NOI18N
        arf_trans_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_trans_jualActionPerformed(evt);
            }
        });
        arf_mtrans.add(arf_trans_jual);

        jMenuBar2.add(arf_mtrans);

        arf_mlap.setText("Laporan");
        arf_mlap.setName("arf_laporan"); // NOI18N

        arf_lap_inti.setText("Laporan Tabel Inti");
        arf_lap_inti.setName("arf_lap_inti"); // NOI18N

        arf_lap_tblbrg.setText("Laporan Tabel Barang");
        arf_lap_tblbrg.setName("arf_lap_tblbrg"); // NOI18N
        arf_lap_tblbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_lap_tblbrgActionPerformed(evt);
            }
        });
        arf_lap_inti.add(arf_lap_tblbrg);

        arf_lap_tblsup.setText("Laporan Tabel Supplier");
        arf_lap_tblsup.setName("arf_lap_tblsup"); // NOI18N
        arf_lap_tblsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_lap_tblsupActionPerformed(evt);
            }
        });
        arf_lap_inti.add(arf_lap_tblsup);

        arf_lap_tblpeg.setText("Laporan Tabel Pegawai");
        arf_lap_tblpeg.setName("arf_lap_tblpeg"); // NOI18N
        arf_lap_tblpeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_lap_tblpegActionPerformed(evt);
            }
        });
        arf_lap_inti.add(arf_lap_tblpeg);

        arf_lap_tblbeli.setText("Laporan Tabel Pembelian");
        arf_lap_tblbeli.setName("arf_lap_tblbeli"); // NOI18N
        arf_lap_tblbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_lap_tblbeliActionPerformed(evt);
            }
        });
        arf_lap_inti.add(arf_lap_tblbeli);

        arf_lap_tbljual.setText("Laporan Tabel Penjualan");
        arf_lap_tbljual.setName("arf_lap_tbljual"); // NOI18N
        arf_lap_tbljual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_lap_tbljualActionPerformed(evt);
            }
        });
        arf_lap_inti.add(arf_lap_tbljual);

        arf_mlap.add(arf_lap_inti);

        arf_lap_gab.setText("Laporan Tabel Gabungan");
        arf_lap_gab.setName("arf_lap_gab"); // NOI18N

        arf_gab2tbl.setText("Laporan Gabungan Dua Tabel");
        arf_gab2tbl.setName("arf_gab2tbl"); // NOI18N
        arf_gab2tbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_gab2tblActionPerformed(evt);
            }
        });
        arf_lap_gab.add(arf_gab2tbl);

        arf_gab3tbl.setText("Laporan Gabungan Tiga Tabel");
        arf_gab3tbl.setName("arf_gab3tbl"); // NOI18N
        arf_gab3tbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_gab3tblActionPerformed(evt);
            }
        });
        arf_lap_gab.add(arf_gab3tbl);

        arf_gab4tbl.setText("Laporan Gabungan Empat Tabel");
        arf_gab4tbl.setName("arf_gab4tbl"); // NOI18N
        arf_gab4tbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_gab4tblActionPerformed(evt);
            }
        });
        arf_lap_gab.add(arf_gab4tbl);

        arf_gab5tbl.setText("Laporan Gabungan Lima Tabel");
        arf_gab5tbl.setName("arf_gab5tbl"); // NOI18N
        arf_gab5tbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arf_gab5tblActionPerformed(evt);
            }
        });
        arf_lap_gab.add(arf_gab5tbl);

        arf_mlap.add(arf_lap_gab);

        jMenuBar2.add(arf_mlap);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(arf_bt_masuk)
                                .addGap(38, 38, 38)
                                .addComponent(arf_bt_batal)
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(arf_username)
                                        .addComponent(arf_password, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                                    .addComponent(jLabel8))))
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(219, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(162, 162, 162)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(arf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arf_bt_masuk)
                    .addComponent(arf_bt_batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(410, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arf_sm_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_sm_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arf_sm_newActionPerformed

    private void arf_sm_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_sm_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arf_sm_saveActionPerformed

    private void arf_mstr_pegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_mstr_pegActionPerformed
        // TODO add your handling code here:
        new Arf_Aplikasi_Master_Pegawai().setVisible(true);
    }//GEN-LAST:event_arf_mstr_pegActionPerformed

    private void arf_gab4tblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_gab4tblActionPerformed
        // TODO add your handling code here:
        String sql = "Select * from arfrvi_vgabungan4tbl";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("arfrvi_rgabungan4tabel.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
        
    }//GEN-LAST:event_arf_gab4tblActionPerformed

    private void arf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arf_usernameActionPerformed

    private void arf_bt_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_bt_masukActionPerformed
        // TODO add your handling code here:
        ArifMasuk();
    }//GEN-LAST:event_arf_bt_masukActionPerformed

    private void arf_bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_bt_batalActionPerformed
        // TODO add your handling code here:
        BersihField();
        SetMenu(true);
        JOptionPane.showMessageDialog(null,"Keluar Akun");
        
    }//GEN-LAST:event_arf_bt_batalActionPerformed

    private void arf_mstr_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_mstr_brgActionPerformed
        // TODO add your handling code here:
        new Aplikasi_Master_Barang().setVisible(true);
    }//GEN-LAST:event_arf_mstr_brgActionPerformed

    private void arf_mstr_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_mstr_supActionPerformed
        // TODO add your handling code here:
        new Arf_Aplikasi_Master_Supplier().setVisible(true);
    }//GEN-LAST:event_arf_mstr_supActionPerformed

    private void arf_trans_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_trans_beliActionPerformed
        // TODO add your handling code here:
        new Arf_Aplikasi_Transaksi_Pembelian().setVisible(true);
    }//GEN-LAST:event_arf_trans_beliActionPerformed

    private void arf_trans_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_trans_jualActionPerformed
        // TODO add your handling code here:
        new Arf_Aplikasi_Transaksi_Penjualan().setVisible(true);
    }//GEN-LAST:event_arf_trans_jualActionPerformed

    private void arf_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arf_usernameKeyPressed

                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            arf_password.requestFocus();
        }
    }//GEN-LAST:event_arf_usernameKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ExitWindow();
    }//GEN-LAST:event_formWindowClosing

    private void arf_lap_tblbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_lap_tblbrgActionPerformed
        // TODO add your handling code here:
String sql = "Select * from arfrvi_barang";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("test1.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_arf_lap_tblbrgActionPerformed

    private void arf_gab2tblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_gab2tblActionPerformed
       String sql = "Select * from arfrvi_vsupplierdanpembelian";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("arfrvi_rsupplierdanpembelian.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_arf_gab2tblActionPerformed

    private void arf_lap_tblsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_lap_tblsupActionPerformed
        // TODO add your handling code here:
        String sql = "Select * from arfrvi_supplier";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("arfrvi_laporansupplier.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_arf_lap_tblsupActionPerformed

    private void arf_lap_tblpegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_lap_tblpegActionPerformed
        // TODO add your handling code here:
        String sql = "Select * from arfrvi_pegawai";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("arfrvi_laporanpegawai.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_arf_lap_tblpegActionPerformed

    private void arf_lap_tblbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_lap_tblbeliActionPerformed
        // TODO add your handling code here:
            String sql = "Select * from arfrvi_pembelian";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("arfrvi_laporanpembelian.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_arf_lap_tblbeliActionPerformed

    private void arf_lap_tbljualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_lap_tbljualActionPerformed
        // TODO add your handling code here:
                String sql = "Select * from arfrvi_penjualan";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("arfrvi_laporanpenjualan.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_arf_lap_tbljualActionPerformed

    private void arf_gab3tblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_gab3tblActionPerformed
        // TODO add your handling code here:
        String sql = "Select * from arfrvi_vgabungan3tabel";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("arfrvi_rgabungan3tabel.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_arf_gab3tblActionPerformed

    private void arf_gab5tblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arf_gab5tblActionPerformed
        // TODO add your handling code here:
                String sql = "Select * from arfrvi_vgabungan5tabel";
    try{
    
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("arfrvi_rgabungan5tabel.jasper"),null, c);
        JasperViewer.viewReport (jp, false);
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_arf_gab5tblActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arf_Aplikasi_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arf_Aplikasi_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arf_Aplikasi_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arf_Aplikasi_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arf_Aplikasi_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arf_bt_batal;
    private javax.swing.JButton arf_bt_masuk;
    private javax.swing.JMenuItem arf_gab2tbl;
    private javax.swing.JMenuItem arf_gab3tbl;
    private javax.swing.JMenuItem arf_gab4tbl;
    private javax.swing.JMenuItem arf_gab5tbl;
    private javax.swing.JMenu arf_lap_gab;
    private javax.swing.JMenu arf_lap_inti;
    private javax.swing.JMenuItem arf_lap_tblbeli;
    private javax.swing.JMenuItem arf_lap_tblbrg;
    private javax.swing.JMenuItem arf_lap_tbljual;
    private javax.swing.JMenuItem arf_lap_tblpeg;
    private javax.swing.JMenuItem arf_lap_tblsup;
    private javax.swing.JMenu arf_mfile;
    private javax.swing.JMenu arf_mlap;
    private javax.swing.JMenu arf_mmaster;
    private javax.swing.JMenuItem arf_mstr_brg;
    private javax.swing.JMenuItem arf_mstr_peg;
    private javax.swing.JMenuItem arf_mstr_sup;
    private javax.swing.JMenu arf_mtrans;
    private javax.swing.JPasswordField arf_password;
    private javax.swing.JMenuItem arf_sm_keluar;
    private javax.swing.JMenuItem arf_sm_new;
    private javax.swing.JMenuItem arf_sm_open;
    private javax.swing.JMenuItem arf_sm_psswrd;
    private javax.swing.JMenuItem arf_sm_save;
    private javax.swing.JMenuItem arf_sm_saveas;
    private javax.swing.JMenuItem arf_trans_beli;
    private javax.swing.JMenuItem arf_trans_jual;
    private javax.swing.JTextField arf_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
